### ISSUE TITLE
Using pollInterval with revalidate

### ISSUE THREAD

**Issue by adamsoffer** [TheRusskiy/next-apollo-ts#2]
Hey @TheRusskiy - quick question. In the readme it states that you can use `revalidate` to update a page every N seconds. Would this negate the need for using `pollInterval` with apollo client?

**Comment by TheRusskiy** [comment]
@adamsoffer this one is different, it's for an initial page load of static pages, you can read more about it here:
https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration
Next.js has pages that are generated on each request, "static" pages that are generated upon initial build, and pages that have "Incremental Static Regeneration" that are cached for N seconds. 
With `pollInterval` apollo client is gonna keep making queries once a page has loaded.

**Comment by adamsoffer** [comment]
Got it. Thanks! How many seconds do you recommend setting revalidate to generally? Is there a rule of thumb here?

**Comment by adamsoffer** [comment]
I have it set to 20 seconds. I'm trying to figure out why sometimes when I load a page in my app it's prerendered as it's supposed to be, and other times I see my loading spinner. Site for context -> https://explorer.livepeer.org/

**Comment by TheRusskiy** [comment]
It's hard to state a general rule. I generally do this: if a page has a lot of personalized content you can make it dynamic instead of static. If you need a page to be very scalable and it doesn't have a lot of personalized content (that can't be pre-generated) you can make it static. If content of this page changes you can add a "revalidate" to it and set the duration to how long users can tolerate stale content. In some cases it can only be a few seconds in other cases even hours.

**Comment by TheRusskiy** [comment]
Unless you have provided static paths pages are going to be generated on demand and then pre-generated upon request as frequently as "revalidate" is set to.

**Comment by TheRusskiy** [comment]
I am going to close this one

**Comment by adamsoffer** [comment]
Got it. Thanks for the info @TheRusskiy !
